POST http://localhost:8000/v1/api/user
Content-Type: application/json

{
    "userId": 2,
    "amount": 50
}

###

POST http://localhost:8000/v1/api/transfer
Content-Type: application/json

{
    "from": "1",
    "to": "1",
    "amount": 10
}